# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: linye's Blog
subtitle: '全端工程師心得分享'
description: 'JavaScript 全端工程師，對電腦相關的東西都有興趣，想了解也想嘗試，興趣是玩金屬樂，所以部落格裡有時還會混入幾篇金屬樂的文章。'
keywords: 前端,後端,全端,網頁,技術,網頁開發,前端開發,後端開發,JavaScript,HTML,python,CSS,metal,NU metal,metal core
author: linyejoe2
language: zh-TW
timezone: 

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://linyejoe2.site/
# https://www.linkedin.com/in/cheng-qing-lin-666542235/ 
# https://leetcode.com/linyejoe2/
# https://www.keybr.com/profile/d1mn1ym
# https://www.credly.com/users/linyejoe2/badges
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  first_line_number: 'inline'
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

sitemap:
  path: sitemap.xml

# Search Setting
# Docs: https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.xml
  field: post
  content: true
  format: html

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment

# 這段給 backup 用的
# deploy:
#   type: git
#   repo: https://github.com/linyejoe2/blog_backup.git
#   branch: master
#   message: "linyejoe2's blog backup"

# 這段是給 deploy bot 用的，常駐
deploy:
  type: git
  repository: git@github.com:linyejoe2/linyejoe2.github.io.git
  branch: master
  message: "update linyejoe2's blog"